# Generated by Django 4.2.16 on 2024-10-22 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artcategories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
