# Generated by Django 4.2.16 on 2024-10-22 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artcategories', '0002_rename_categories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artcategories.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='type',
            name='image',
            field=models.ImageField(upload_to='uploads/types/'),
        ),
    ]
